---
CoreConfig:
  TC_Iterations: 3
  MaxTimeS: 1800
  LocalPath: "../../perf_baseline_quick/"
  RemotePath: "/var/log/charon.log"
  CommandRetries: 2
  TrafficCommand: "ping -c 2 10.1.0.2"
  PrintLevel: 1
  compose_files: "./pq-strongswan/docker-compose.yml"
  Note: "baseline-quick"
