services:
  moon:
    image: strongx509/pq-strongswan:latest
    container_name: moon
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    sysctls:
      net.ipv4.ip_forward: "1"
    volumes:
      - ./moon:/etc/swanctl
      - ./moon/swanctl_hybrid1pq.conf:/etc/swanctl/swanctl.conf
      - ./strongswan.conf:/etc/strongswan.conf
    networks:
      internet:
         ipv4_address: 192.168.0.2
      intranet:
         ipv4_address: 10.1.0.2
  carol:
    image: strongx509/pq-strongswan:latest
    container_name: carol
    depends_on:
      - moon
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./carol:/etc/swanctl
      - ./carol/swanctl_hybrid1pq.conf:/etc/swanctl/swanctl.conf
      - ./strongswan.conf:/etc/strongswan.conf
    networks:
      internet:
         ipv4_address: 192.168.0.3
  lanhost:
    image: strongx509/pq-strongswan:latest
    container_name: lanhost
    depends_on:
      - moon
    cap_add:
      - NET_ADMIN
    command:
      - /bin/bash
      - -lc
      - ip route replace 10.3.0.0/24 via 10.1.0.2 && tail -f /dev/null
    stdin_open: true
    tty: true
    networks:
      intranet:
         ipv4_address: 10.1.0.3

networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  intranet:
     ipam:
        driver: default
        config:
          - subnet: 10.1.0.0/24
